version: '3.6'
services:

  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '2022:22'
      - '50000:50000'
    volumes:
      - $HOME/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - $HOME/jenkins/logs/nginx:/var/log/nginx
#      - ${NGINX_SSL_CERT:-./certs/self_signed_cert.pem}:/etc/nginx/ssl/server.crt # uncomment for SSL
#      - ${NGINX_SSL_KEY:-./certs/self_signed_key.pem}:/etc/nginx/ssl/server.key   # uncomment for SSL
    restart: always

  registry:
    image: registry:2
    container_name: registry
    ports:
      - '5000:5000'
    volumes:
      - $HOME/jenkins/registry:/var/lib/registry
    restart: always
#
# FYI to use insecure (http) registry on host and agent machines you may want to add something like
#{
#  "insecure-registries" : ["10.0.111.123:5000"]
#}
# to [/etc/docker/daemon.json] and restart docker [sudo service docker restart].
